// Frameworks_librerias_js/svelte/myapp/src/Form.svelte
<script>
 const movies = [
              {
                name: "Batman",
                available: 5,
                quantity: 0,
              },
              {
                name: "Hombre del Norte",
                available: 4,
                quantity: 0,
              },
              {
                name: "Capitan America",
                available: 10,
                quantity: 0,
              },
            ];

</script>

{#each movies as movie}
<form>
  <h3>{movie.name}</h3>
  <button type="button" on:click={()=>movie.quantity -=1} disabled={movie.quantity <=0}>
    -
  </button>
  {movie.quantity}  
  <button type="button" on:click={()=>movie.quantity +=1} disabled={movie.quantity >= movie.available}>
    +
  </button>

 </form>
{/each}

// Frameworks_librerias_js/demo-react/src/Form.js

import React from 'react'

export default function form (props) {

//react hook

// eslint-disable-next-line react-hooks/rules-of-hooks
const [quantity, setQuantity] = React.useState(0);

  const{movie}= props;

  return (
    <form>
        <h3>{movie.name}</h3>
     
        <button type='button'onClick={()=>setQuantity(quantity -1)} disabled={quantity <= 0}>-</button>
        {quantity}
        <button type='button' onClick={()=>setQuantity(quantity +1)} disabled={quantity >= movie.available}>+</button>
    </form>




  );
}
